name: on_push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:

  test:
    name: Test Code
    runs-on: ubuntu-latest
    env:
      GO_VERSION: '1.25'
      LINTER_VERSION: '1.53.3'
      GOLANGCI_LINT_VERSION: v2.6
      SCAN_SEVERITY: 'MEDIUM'
    steps:

      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      # Setup, Test, and Lint
      - name: Run Go CI (setup, test, lint)
        uses: ./.github/actions/go-ci
        with:
          go_version: '${{ env.GO_VERSION }}'
          golangci_lint_version: '${{ env.GOLANGCI_LINT_VERSION }}'
          upload_codecov: 'true'

      # Scan for Vulnerabilities
      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8  # v0.33.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          hide-progress: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: ${{ env.SCAN_SEVERITY }}
          exit-code: '0'
        continue-on-error: true
      - name: Upload Trivy Results to GitHub Security
        if: always() && hashFiles('trivy-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@16df4fbc19aea13d921737861d6c622bf3cefe23  # v2.23.0
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy-fs'