name: on_tag
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'  # Only build tag with semantic versioning format

permissions:
  attestations: write
  contents: write
  id-token: write
  packages: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO_VERSION: '1.25'
      GOLANGCI_LINT_VERSION: v2.6
      CRANE_VERSION: 'v0.20.6'
      IDENTITY_PROVIDER: 'projects/116689922666/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
      PROJECT_ID: 'eidosx'
      SERVICE_ACCOUNT: 'github-actions-user'
      RUN_REGION: 'us-west1'
      RUN_SERVICE: 'api'
      RUN_IMAGE_REG: 'us-docker.pkg.dev/eidosx/eidos/mchmarny'
    steps:

      # Setup, Test, and Lint
      - name: Run Go CI (setup, test, lint)
        uses: ./.github/actions/go-ci
        with:
          go_version: '${{ env.GO_VERSION }}'
          golangci_lint_version: '${{ env.GOLANGCI_LINT_VERSION }}'
          upload_codecov: 'false'

      - name: Install ko
        uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d  # v0.9

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@43a17d6e7add2b5535efe4dcae9952337c479a93  # v0.20.11

      - name: Authenticate
        shell: bash
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | ko login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a  # v6.4.0
        with:
          install-only: true

      - name: Build and Release
        id: release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KO_DOCKER_REPO: ''
        run: make release

      - name: Attest eidos-api-server image
        uses: ./.github/actions/attest-image-from-tag
        with:
          image_name: ghcr.io/${{ github.repository_owner }}/eidos-api-server
          tag: ${{ github.ref_name }}
          crane_version: ${{ env.CRANE_VERSION }}

      - name: Attest eidos image
        uses: ./.github/actions/attest-image-from-tag
        with:
          image_name: ghcr.io/${{ github.repository_owner }}/eidos
          tag: ${{ github.ref_name }}
          crane_version: ${{ env.CRANE_VERSION }}

      # Deploy to Cloud Run
      - name: Deploy API to Cloud Run
        if: steps.release.outcome == 'success'
        uses: ./.github/actions/cloud-run-deploy
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.IDENTITY_PROVIDER }}
          service_account: "${{ env.SERVICE_ACCOUNT }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"
          region: ${{ env.RUN_REGION }}
          service: ${{ env.RUN_SERVICE }}
          image: "${{ env.RUN_IMAGE_REG }}/eidos-api-server:${{ github.ref_name }}"